/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package garagemechanic;

/**
 *
 * @author Mark
 */
public class MainWindowFrame extends javax.swing.JFrame {
    GarageMechanicProgram currentGarageMechanicProgram; // used by various frames within program 
    /**
     * Creates new form MainWindowFrame
     */
    public MainWindowFrame(GarageMechanicProgram incomingGarageMechanicProgram) {
        this.currentGarageMechanicProgram = incomingGarageMechanicProgram;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        currentMechanicLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        fileNewMechanicItem = new javax.swing.JMenuItem();
        fileOpenMechanicItem = new javax.swing.JMenuItem();
        fileSaveMechanicItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileMenuQuitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        helpAboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        currentMechanicLabel.setText("Current Mechanic:");

        jLabel1.setText( "HUH"+ currentGarageMechanicProgram.getMechanicName());

        jMenu1.setText("File");

        fileNewMechanicItem.setText("New Mechanic");
        fileNewMechanicItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewMechanicItemActionPerformed(evt);
            }
        });
        jMenu1.add(fileNewMechanicItem);

        fileOpenMechanicItem.setText("Open Mechanic");
        jMenu1.add(fileOpenMechanicItem);

        fileSaveMechanicItem.setText("Save Mechanic");
        jMenu1.add(fileSaveMechanicItem);
        jMenu1.add(jSeparator1);

        fileMenuQuitItem.setText("Quit ");
        fileMenuQuitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuQuitItemActionPerformed(evt);
            }
        });
        jMenu1.add(fileMenuQuitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        helpAboutMenuItem.setText("About");
        helpAboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpAboutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(helpAboutMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentMechanicLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentMechanicLabel)
                    .addComponent(jLabel1))
                .addGap(0, 565, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuQuitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuQuitItemActionPerformed
        // If the user presses this, let's kill the app
        // @TODO let's be graceful in the future...
        System.exit(0);
    }//GEN-LAST:event_fileMenuQuitItemActionPerformed

    private void helpAboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpAboutMenuItemActionPerformed
        // Create and make appear an About Window Frame!
        AboutWindowFrame aboutWindowFrameVar = new AboutWindowFrame();
        aboutWindowFrameVar.setVisible(true);;
    }//GEN-LAST:event_helpAboutMenuItemActionPerformed

    private void fileNewMechanicItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewMechanicItemActionPerformed
        // TODO add your handling code here:
        NewMechanicWindowFrame newMechanicWindowFrameVar = new NewMechanicWindowFrame(currentGarageMechanicProgram);
        newMechanicWindowFrameVar.setVisible(true);
    }//GEN-LAST:event_fileNewMechanicItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindowFrame().setVisible(true);
            }
        });*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentMechanicLabel;
    private javax.swing.JMenuItem fileMenuQuitItem;
    private javax.swing.JMenuItem fileNewMechanicItem;
    private javax.swing.JMenuItem fileOpenMechanicItem;
    private javax.swing.JMenuItem fileSaveMechanicItem;
    private javax.swing.JMenuItem helpAboutMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
